language: ruby
cache: bundler
rvm:
  - 2.5.3
script:
  - bundle exec jekyll build
  - bundle exec rake test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: _site
  on:
    branch: master
