language: ruby
cache: bundler
rvm: 2.6.3

matrix:
  fast_finish: true
  allow_failures:
    - rvm: latest
    - rvm: 2.6.3
      script: 
      - bundle exec jekyll build
      - bundle exec rake test

script: bundle exec jekyll build
deploy: 
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: _site
  on:
    branch: master