language: ruby
cache: bundler
rvm:
  - 2.6.3
jobs:
  include:
    - name: "Successful Build"
      script: bundle exec jekyll build
  allow_failures:
    - name: "Rake/HTMLProofer Test"
      script: 
      - bundle exec jekyll build
      - bundle exec rake test

deploy: 
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: _site
  on:
    branch: master