language: ruby
cache: bundler
rvm: 
  - 2.6.3
  - latest

matrix:
  fast_finish: true
  allow_failures:
    - rvm: latest

script: bundle exec jekyll build
deploy: 
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: _site
  on:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: always