title: ACM Teach LA
email: acmteachla@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A subcommittee of UCLA ACM, ACM Teach LA pairs UCLA undergraduates with schools in Los Angeles to provide free coding classes for students. Our goal is to empower all students with the ability to code and make a difference.
baseurl: "/teach-la-website" # the subpath of your site, e.g. /blog
url: "uclaacm.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: uclaacm
github_username:  uclaacm
facebook_username: teachlaucla
editor_link: https://uclaacm.github.io/TeachLAFrontend/

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
sass:
  sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - Rakefile
  - LICENSE